### ISSUE TITLE
First argument of the last command

### ISSUE THREAD

**Issue by zhonglism** [amir-jafari/Cloud-Computing#1]
For the $sudo ./install-14-04-final1.sh <netid or username of ssh key> command, is the first argument the current username of the instance? For example, in the gcp instance, it is chunxu@instance-1, so the first argument should be chunxu?

**Comment by mikearango** [comment]
Yes, the first argument to the shell script should be the username of your instance. This is why it is recommended to specify a username when you create the ssh key.

**Comment by mikearango** [comment]
@zhonglism Let me know if the above comment answers your question and I will close the issue if that is the case.
